# Server
server.port=8080

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://postgres:5432/customeredp_db
spring.datasource.username=customer_admin
spring.datasource.password=Cust@2026#Secure
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (προσωρινό - σε production θα μπαίνει σε environment variable)
jwt.secret=mySuperSecretKey12345678901234567890
jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Logging
logging.level.com.customeredp=DEBUG