services:
  postgres:
    image: postgres:16-alpine
    container_name: customeredp-db
    environment:
      POSTGRES_USER: customer_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: customeredp_db
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "password_encryption=md5", "-c", "listen_addresses=*"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  java-service:
    build: ./java-service
    container_name: customeredp-java
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customeredp_db
      SPRING_DATASOURCE_USERNAME: customer_admin
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: mySuperSecretKey12345678901234567890
    depends_on:
      - postgres

  python-service:
    build: ./python-service
    container_name: customeredp-python
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://customer_admin:${POSTGRES_PASSWORD}@postgres:5432/customeredp_db
    depends_on:
      - postgres

  csharp-service:
    build: ./csharp-service
    container_name: customeredp-csharp
    ports:
      - "5000:8080"
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=customeredp_db;Username=customer_admin;Password=${POSTGRES_PASSWORD}
    depends_on:
      - postgres

volumes:
  postgres_data: